# Generated by Django 3.1.6 on 2021-03-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='title',
            new_name='work',
        ),
    ]
